### ISSUE TITLE
Icdrama Error on 25/7/2017

### ISSUE THREAD

**Issue by casperooi** [aznhusband/aznhusband.github.io#1]
Hi boss,
I am currently facing ICDrama issue, with the error message: ICDrama error while opening any drama. It happened sicne 25/7, previously was working fine. My current version is 1.3.0, Any findings?

Thank you.

**Comment by dumbo0001** [comment]
Any success @aznhusband ? I also took a quick look at the changes. A bit hard to read the source of the page.

**Comment by aznhusband** [comment]
I've released 1.4.0 in the last couple of hours.  Give it a try.

**Comment by dumbo0001** [comment]
Great work! I'm going to check your changes. I couldn't find an easy way to find the post data so couldn't help you.

**Comment by jason-ong** [comment]
@aznhusband 
Have some issue, cant open any video.

v1.4.0 icdrama
