### ISSUE TITLE
icdrama addon down 

### ISSUE THREAD

**Issue by xlemonWong** [aznhusband/aznhusband.github.io#12]
icdrama addon down as on 2018-7-31 8:40am PST, please fix.

Thank you very much

**Comment by aznhusband** [comment]
OK, I'll have a look over the next day or so.

**Comment by zmingxie** [comment]
Confirmed, https://github.com/aznhusband/aznhusband.github.io/pull/13 fixed the issue. 🎉

**Comment by xlemonWong** [comment]
1.8.3 fixed the issue.  Thank you very much for the quick response.

**Comment by xlemonWong** [comment]
It is down again, please fix.
Thank you!

**Comment by xlemonWong** [comment]
1.8.4 is working.  thank you.
