### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jkfoong** [aznhusband/aznhusband.github.io#23]
Cant play video since yesterday.

**Comment by jkfoong** [comment]
18:33:06.946 T:18592  NOTICE: URLResolver: Initializing URLResolver version: 5.0.10
18:33:07.652 T:18592   ERROR: URLResolver: AttributeError Error - From: Icdrama Link: http://icdrama.to/vidembed._AjclK2Az5MvvvtlUAhaaQ.html: 'NoneType' object has no attribute 'startswith'
18:33:07.653 T:18592   ERROR: URLResolver: AttributeError Error - From: Icdrama Link: http://icdrama.to/watch-online-life-on-the-line-episode-23-114076.html: 'NoneType' object has no attribute 'startswith'
18:33:07.696 T:17028   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.icdrama/?action=mirrors&url=http%3a%2f%2ficdrama.to%2fwatch-online-life-on-the-line-episode-23-114076.html
18:33:07.698 T:17028   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.icdrama/?action=mirrors&url=http%3a%2f%2ficdrama.to%2fwatch-online-life-on-the-line-episode-23-114076.html) failed

**Comment by xlemonWong** [comment]
Same problem here

**Comment by boleanly** [comment]
Made a quick fix here #24

**Comment by aznhusband** [comment]
I'll release and close this issue when I get home later tonight.  All these women around the world anxiously awaiting our favours, eh, boleanly?  ;)

**Comment by aznhusband** [comment]
Released 1.9.4

**Comment by xlemonWong** [comment]
thank you
