### ISSUE TITLE
Alternative address

### ISSUE THREAD

**Issue by leckylao** [aznhusband/aznhusband.github.io#25]
I remember in the early version was able to switch different domain. But not anymore now. Could you reenable this ASAP please? As the Reddit forum point out that in Australia the icdrama.se is blocked by ISP. But icdrama.to is available

**Comment by leckylao** [comment]
@boleanly OK, will try that. And yes, it needs to have an option to switch between different domains in the plug in settings. Which I remember it used to have this option.

**Comment by leckylao** [comment]
Hi @boleanly, @aznhusband , 

Just noticed On 13rd Nov, icdrama.to has already been added into domains. But V1.9.4 still not work as base_url still using icdrama.se for users in Australia. 

- As @boleanly point out the icdrama.se is just redirect then could you change the base_url to use to and pump that version for a quick fix please?
- Can I ask about the differences between base_url and domains please? As it seems a bit duplicate that maybe base_url can be set from domains?

**Comment by tvbviewer** [comment]
Hi @boleanly and @aznhusband  - first, thank you for all you do.  Been trying to troubleshoot this myself and couldn't get the fix to work.  Seems like we started having the ISP issue with blocking icdrama.se but I can navigate to icdrama.to.  Is there anyway you can push out an update so the base_url is icdrama.to?  I am running this on a Firestick and cannot figure out how to update the file myself on the device (but I can see the file on my laptop that needs to be updated).

Any advice for a non-techical person would be great.  Thanks!

**Comment by leckylao** [comment]
@tvbviewer I found a better solution now using RSS Player, more stable and less blocking.
