### ISSUE TITLE
Icdrama 1.9.6 Error 

### ISSUE THREAD

**Issue by NichiAtkins** [aznhusband/aznhusband.github.io#34]
I just installed Kodi 19 and then installed the Icdrama 1.9.6 addon. I got an error so I uninstalled then reinstalled Icdrama again and I keep getting the same error:
![15753122470642770676139671478166](https://user-images.githubusercontent.com/28831178/69985771-e212e700-1509-11ea-95ab-02c6b0263c4c.jpg)

HELP ME PLEEEEEEEEASE!!!!!!!!!!!!!! MY SON AND I LOVE WATCHING ASIAN SHOWS/MOVIES
Thanks

**Comment by PtahX** [comment]
Sounds like a Beautiful Soup error  I'm not sure what platform your are and I don't have Kodi 19 running yet to test it out. if you have a pc try running "pip install beautifulsoup4" or "pip install soupsieve". I'm guessing its a dependency issue

**Comment by NichiAtkins** [comment]
I'm using an Amazon firestick on my Samsung TV. Can I check for a
dependency on the firestick? Can I run the pip install on a firestick?

**Comment by PtahX** [comment]
Use Downloader app free from the Amazon Store . Go to: http://mirrors.kodi.tv/addons/krypton/script.module.beautifulsoup/ then download the APK there and install.  That will hopefully solve the issue :)
