### ISSUE TITLE
Subtitle [English] does not match the Korean Drama "Touch."

### ISSUE THREAD

**Issue by sammydc77** [aznhusband/aznhusband.github.io#37]
I came across this one last week, at that time there were no subtitles [English].  I thought to wait until it was added.  Thank You.  Unfortunately S01E01, may be the right the correct Sub, but runs about 10 minutes early, or may even be the wrong Sub.  Please review.

I really appreciate the Korean Dramas, though I find the only way to keep track of which I have watched is to search another Kodi App, in my Favorites, and mark "watched in Trakt," after each episode.

**Comment by aznhusband** [comment]
I just scrape the data, if it's wrong on the site, not much I can do.

**Comment by sammydc77** [comment]
It had been fixed, some months ago, but thanx for looking at it.  It would
be nice to be able to mark as "Watched."

Joseph
