### ISSUE TITLE
Conversion to Python 3?

### ISSUE THREAD

**Issue by PtahX** [aznhusband/aznhusband.github.io#38]
I wiped one of my Kodi boxes (18.6) today and went to add IcDrama and I'm getting the following error. I assume it's related to the push towards Python 3 - anyone working on an IcDrama conversion to Py 3 yet for the next Kodi 19 versions?

"ERROR: CAddonInstallJob[plugin.video.icdrama]: The dependency on xbmc.python version 3.0.0 could not be satisfied."

[https://forum.kodi.tv/showthread.php?tid=351745](url)
[https://kodi.tv/article/kodi-19-python-3-goes-live](url)

**Comment by boleanly** [comment]
I think it's detecting the xbmc.python version entry in addon.xml. First thing to do is change that to 3.0.0 . Not sure if there's gonna be code issues though

**Comment by PtahX** [comment]
I'm attempting to see if I can get it going on a testing branch so far I've updated 
xbmc.python to 3.0.0 and have been attempting a few other things. It appears it will be more involved as I'm still seeing the same error. I have a draft pull request there but I'm not sure it's worth uploading at this point. 

Standard disclaimer - I'm a rookie just learning & trying ot help where I can ;)

**Comment by boleanly** [comment]
@PtahX Looking into it more, I think it's cause one of the dependencies (required addons) wants to use Python 3 but the Kodi 18.6 build only has Python 2. Are you using Kodi 18.6? You'll want to revert the addon.xml change, sorry about that. Not sure which dependency is the culprit though. It's probably the ones being downloaded from the official repo.

https://kodi.wiki/view/Addon.xml#Dependency_versions

**Comment by PtahX** [comment]
@boleanly I’m still running 18.6 on the new Nvidia Shield, that would definitely make sense. I’ll see if I can figure out which it is, I'll post what I find for reference either way. :beer:

**Comment by PtahX** [comment]
That was it, the culprit was  `<import addon="script.module.beautifulsoup4"`.  Something to do with my cache file I expect.

**To fix on the Shield:** 
Go into NVidia Shield Settings / Apps / Kodi and click Clear Cache.

**to fix in Windows 10:**
type %appdata% in search
find your Kodi directory
\AppData\Roaming\Kodi\ 
delete the "cache" file
then reinstall IcDrama

**Comment by boleanly** [comment]
Nice, good job! Thanks for the info :+1:

**Comment by sergiobaiao** [comment]
> I'm playing around to see if I can get it going on a testing branch so far I've updated
> xbmc.python to 3.0.0 and have been attempting a few other things. It appears it will be more involved as I'm still seeing the same error. I have a draft pull request there but I'm not sure it's worth uploading at this point.
> 
> Standard disclaimer - I'm a rookie just learning & trying ot help where I can ;)

Can you tell how you updated xbmc.python to 3.0.0?

**Comment by PtahX** [comment]
> Can you tell how you updated xbmc.python to 3.0.0?

To do it properly someone would need to convert all the old Python 2 code (basically the whole module) into Python 3 code. It’s a fairly involved process, you can read up on it on the kodi forums [https://forum.kodi.tv/forumdisplay.php?fid=281](url)
