### ISSUE TITLE
Icdrama 1.9.6 but drama not updated

### ISSUE THREAD

**Issue by Optimus2202** [aznhusband/aznhusband.github.io#40]
I am a non-technical person, please help.

I have icdrama ver 1.9.6 running on kodi leia (on firestick). The updates on the dramas/movies has stopped even though I am on ver 1.9.6.  I cannot watch new dramas or movies.  For example, I was watching the Chinese drama "Love By Hypnotic" and it is only up to Episode 24 (total episodes are 36).
I have tried deleting and reinstalling icdrama. Still the same list of drama/movie.

I don't understand why. It is ver 1.9.6 and working. But the dramas/movies are not updated.  I can only watch old dramas/movies.

**Comment by PtahX** [comment]
I took a look, that isn't an issue with the icdrama Kodi addon itself - the source feed that Icdrama is reading is only showing up to episode 24 at this point. They often lag behind on the shows then add several all at once when they get access to them. Aznhusbands Icdrama Kodi app doesn’t actually host any content at all - it’s simply reading external feeds to transfer the shows into Kodi without all the adverts and such.  

I did find your show with full updated episodes at [https://kissasian.sh/Drama/The-Love-by-Hypnotic](url) you can stream it for free from there but I haven’t seen a scraper that will port it into kodi as of yet. 

Cheers :)
PtahX

**Comment by Optimus2202** [comment]
Thank you PtahX. I only used that drama as an example but if you think it's Kodi reading the external feeds, it has not been doing that for over a year already because I think this position has been like this for over a year.  So, it's a Kodi issue then? And that's nothing I can do? Sigh.....
Yes, I have the kissasian app on my tablet (thank you for letting me know), and it's updated. Just that I like to use icdrama addon on Kodi because I can watch it on my TV with a bigger screen.

**Comment by aznhusband** [comment]
I'll close this bug, since it's not really an Icdrama bug.
