### ISSUE TITLE
icdrama error

### ISSUE THREAD

**Issue by du2uxh** [aznhusband/aznhusband.github.io#44]
I am having error on this kodi plugin icdrama even using a url resolver.  It looks like the url had changed from icdrama to adrama.  What is needed to change it from icdrama to adrama manually?  Not so good on Linux but can manage to go around directories and editing files.  Please help.

**Comment by alawnyc** [comment]
Same issue here please help

**Comment by lluxia** [comment]
Hello,
I've also been having the same issue the last two days.

**Comment by brianmus** [comment]
yes. got the same issue 2 days ago

**Comment by aznhusband** [comment]
Do you people even LOOK at the other bugs?!  We've already got one open on this.

Closing.  Do a little reading, people.
