### ISSUE TITLE
Can't Install from Repository

### ISSUE THREAD

**Issue by qauff** [aznhusband/aznhusband.github.io#49]
I am getting a "Could not connect to repository." error when I try to Install from Repository.

Looking at the [addons.xml](https://github.com/aznhusband/aznhusband.github.io/blob/master/addons.xml#L4), looks like there's an XML parsing issue. You can't have two XML delcarations in the file.

```
<?xml ... ?>
```

I'm assuming [this](https://github.com/aznhusband/aznhusband.github.io/blob/master/addons.xml#L4) is the file referenced here https://aznhusband.github.io/addons.xml

I'd submit a PR myself, but I'm not sure what the steps to build for dists are for deploying to azhusband.github.io.

**Comment by xalagaco** [comment]
This add-on installs fine for most and hasn't changed in months.
This is a trouble ticketing system for reporting software issues.
You should ask in the Reddit forum for installation help.

My suggestion is to "Uninstall the Repo", confirm the source in File manager,
"Install from zip file", and "Install from repository". Otherwise, try Reddit.

Please close this ticket. Thank you.

**Comment by qauff** [comment]
@xalagaco the add-on updates if you've already got it installed. Just telling you from the perspective of a brand new user 😄 

https://github.com/aznhusband/aznhusband.github.io/blame/8b4cbc3bce6048c86a8ae523523b0fe3f56ef4a9/addons.xml#L4

You can see in this git blame that an extra xml declaration was added, and it's causing XML parsing issues.

I wasn't aware there is a subreddit for the addon, can you point me in the right direction? I'll close the ticket after I create a thread there.

**Comment by qauff** [comment]
Found the release thread on Reddit: https://www.reddit.com/r/Addons4Kodi/comments/gypbcu/icdrama_210_released/

It looks like I'm not the only person having this issue. Removing the extra XML declaration should fix this.

**Comment by xalagaco** [comment]
> @xalagaco the add-on updates if you've already got it installed. Just telling you from the perspective of a brand new user 😄 

Of course that's the point of a repo, except 2.1.0  required a repo reinstall due to dependency changes.

> You can see in this git blame that an extra xml declaration was added, and it's causing XML parsing issues.

It works fine for me on Windows 10 and firestick the way it is.

> I wasn't aware there is a subreddit for the addon, can you point me in the right direction? I'll close the ticket after I create a thread there.

I see you found one.
