### ISSUE TITLE
Icdrama not work

### ISSUE THREAD

**Issue by tofufi** [aznhusband/aznhusband.github.io#54]
I used Kodi to see icdrama but just down, any one help here???? Thx

**Comment by tofufi** [comment]
Sorry, fault alarm. my other device work fine, let me double check

Thx

> I used Kodi to see icdrama but just down, any one help here???? Thx

**Comment by boleanly** [comment]
I think the website was having issues yesterday. Website issues are unrelated to the addon

Edit: Website/server issues can't be fixed by the addon*

**Comment by tofufi** [comment]
Thx for clarify


Sent from Yahoo Mail for iPhone


On Tuesday, February 2, 2021, 1:53 PM, boleanly <notifications@github.com> wrote:




I think the website was having issues yesterday. Website issues are unrelated to the addon

**Comment by xalagaco** [comment]
Please close ticket you created.

**Comment by tofufi** [comment]
fault alarm
