### ISSUE TITLE
Error when trying to play video

### ISSUE THREAD

**Issue by sounami** [aznhusband/aznhusband.github.io#7]
This just started getting thrown sometime yesterday.

Here's what I'm seeing in the kodi.log:

```
ERROR : URLResolver: NameError Error - From: Videobug Link: 
http://videobug.se/v/E2NnkLxIQMLIXb3K1uyOkA: global name 'url' is not defined
ERROR : URLResolver: AttributeError Error - From: 
Icdrama Link: http://icdrama.se/watch-online-daddy-cool-episode-01-98456.html: 'NoneType' object has no attribute 'startswith'
```

**Comment by aznhusband** [comment]
Try version 1.8.0

**Comment by CLFNole** [comment]
You’re a lifesaver. Trying to explain how an addon gets updated to my wife and mother-in-law doesn’t go very far.

**Comment by sounami** [comment]
Looks like it's working now!

Had to update via direct download though, updating via repo only shows 1.7.0

Thanks for the hard work you're putting into this!
