### ISSUE TITLE
Error when trying to play video

### ISSUE THREAD

**Issue by djnvee** [aznhusband/aznhusband.github.io#8]
Hello having issues trying to play video on kodi 16

This is the error on the log
InsecurePlatformWarning
22:40:54 T:1609689376   ERROR: URLResolver: SSLError Error - From: Videobug Link: http://videobug.se/v/fkn-OTl2HEK5sg6BQrqxMg: hostname 'href.li' doesn't match either of '*.wordpress.com', 'wordpress.com'
22:40:54 T:1609689376   ERROR: URLResolver: AttributeError Error - From: Icdrama Link: http://icdrama.se/watch-online-my-mister-episode-06-98741.html: 'NoneType' object has no attribute 'startswith'
22:40:55 T:1542449440   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.icdrama/?action=mirrors&url=http%3a%2f%2ficdrama.se%2fwatch-online-my-mister-episode-06-98741.html
22:40:55 T:1542449440   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.icdrama/?action=mirrors&url=http%3a%2f%2ficdrama.se%2fwatch-online-my-mister-episode-06-98741.html) failed
22:42:23 T:1542449440   ERROR: Control 61 in window 10147 has been asked to focus, but it can't

**Comment by aznhusband** [comment]
Unfortunately, ICdrama has moved to https links, which Kodi 16 doesn't support.  You'll have to update to kodi 17
